---
title: "Math skills and microstructure of the middle longitudinal fasciculus: A developmental investigation. Statistical analysis: ANOVA."
author: "Irina Buianova, Asya Istomina"
date: "January 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Install necessary packages
if(!requireNamespace("readr", quietly = TRUE)) install.packages("readr")
if(!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")

# Load necessary libraries
library(readr)  # For reading CSV files
library(dplyr)  # For data manipulation
library(stats)  # For ANOVA analysis
```
Load the Data
```{r}
file_path <- "/Users/asyaistomina/Desktop/DTI_PMT_STAT/DTI+MATH+AGE+GROUPS.csv"
data <- read_csv(file_path)
```
ANOVA
```{r}
# Specify the columns for ANOVA
columns_of_interest <- c("FA_lh_mlf", "FA_rh_mlf", "MD_lh_mlf", "MD_rh_mlf", "RD_lh_mlf", "RD_rh_mlf", 
                         "AD_lh_mlf", "AD_rh_mlf", "age123", 
                         "ADD1", "ADD2", "ADD3", "SUB1", "SUB2", "SUB3", "MUL1", "MUL2", "MUL3", 
                         "DIV1", "DIV2", "DIV3", 
                         "RT_ADD1", "RT_ADD2", "RT_ADD3", "RT_SUB1", "RT_SUB2", "RT_SUB3", 
                         "RT_MUL1", "RT_MUL2", "RT_MUL3", "RT_DIV1", "RT_DIV2", "RT_DIV3")

# Perform ANOVA for each column based on age123 groups
for (column in columns_of_interest) {
  anova_result <- aov(as.formula(paste(column, " ~ factor(age123)")), data = data)
  print(paste("ANOVA for", column))
  print(summary(anova_result))
}
```
Post Hoc Analysis
```{r}
# Convert 'age123' to a factor
data$age123 <- as.factor(data$age123)

# Specify the variables for analysis
variables <- c("FA_lh_mlf", "FA_rh_mlf", "MD_lh_mlf", "MD_rh_mlf", "RD_lh_mlf", "RD_rh_mlf",
               "AD_lh_mlf", "AD_rh_mlf", "ADD1", "ADD2", "ADD3", "SUB1", "SUB2", "SUB3",
               "MUL1", "MUL2", "MUL3", "DIV1", "DIV2", "DIV3", 
               "RT_ADD1", "RT_ADD2", "RT_ADD3", "RT_SUB1", "RT_SUB2", "RT_SUB3",
               "RT_MUL1", "RT_MUL2", "RT_MUL3", "RT_DIV1", "RT_DIV2", "RT_DIV3")

# Loop through each variable and perform ANOVA and Tukey's HSD test
for (variable in variables) {
  # Perform ANOVA for the variable
  model <- aov(as.formula(paste(variable, "~ age123")), data = data)
  anova_result <- summary(model)
  
  # Extract the p-value from the ANOVA result
  p_value <- anova_result[[1]]$`Pr(>F)`[1]
  
  # Check if the ANOVA result is significant (p-value less than 0.05)
  if (p_value < 0.05) {
    # Perform Tukey's HSD test
    tukey_result <- TukeyHSD(model)
    
    # Print the Tukey's HSD test result
    print(paste("Tukey's HSD test for", variable))
    print(tukey_result)
  } else {
    cat("ANOVA result for", variable, "is not significant (p-value > 0.05). No Tukey's HSD test performed.\n")
  }
}
```

cc